[package]
name = "reseam-sign"
version.workspace = true
edition = "2021"
description = "APK signing for Reseam with Android Signature Scheme v2"
readme = "README.md"

[dependencies]
memmap2 = { workspace = true }
ring      = { workspace = true }
rayon     = { workspace = true }
thiserror = { workspace = true }
tracing   = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
zip      = { workspace = true }
