import { resolve } from 'node:path';
import { mkdir, copyFile, writeFile, rm } from 'node:fs/promises';
const browser = resolve(import.meta.dir, '..');
const files = ['reseam_sdk_browser.wasm', 'methods.json', 'reseam-runtime.jar', 'browser-host.jar'];
const assets: Record<string, { path: string; sha256: string; size: number }> = {};
for (const path of files) {
  const bytes = await Bun.file(resolve(browser, 'build/runtime', path)).arrayBuffer();
  const sha256 = new Bun.CryptoHasher('sha256').update(bytes).digest('hex');
  assets[path] = { path, sha256, size: bytes.byteLength };
}
const release = new Bun.CryptoHasher('sha256').update(JSON.stringify(assets)).digest('hex').slice(0, 20);
const base = `runtime/${release}/`;
await rm(resolve(browser, 'public/runtime'), { recursive: true, force: true });
await mkdir(resolve(browser, 'public', base), { recursive: true });
for (const path of files) await copyFile(resolve(browser, 'build/runtime', path), resolve(browser, 'public', base, path));
await writeFile(resolve(browser, 'src/runtime.generated.ts'), `// Generated by scripts/package-runtime.ts. Do not edit.\nexport const runtime = ${JSON.stringify({ base, assets }, null, 2)} as const;\n`);
console.log(`Packaged browser runtime ${release}`);
