[package]
name = "stitch-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "stitch"
path = "src/main.rs"

[dependencies]
stitch-patcher = { workspace = true, features = ["kotlin"] }
stitch-sign    = { workspace = true }
stitch-apk     = { workspace = true }
clap           = { workspace = true }
anyhow         = { workspace = true }
tempfile       = { workspace = true }
tracing        = { workspace = true }
tracing-subscriber = { workspace = true }
