[package]
name = "reseam-hermes"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Borrowed Hermes bytecode parsing, linking, and editing"
license = "GPL-3.0-or-later"

[dependencies]
thiserror.workspace = true
ring.workspace = true
rustc-hash.workspace = true

[lints]
workspace = true
