[package]
name = "reseam-dex"
version.workspace = true
edition = "2021"
description = "A high-performance DEX file parser, writer, and mutator"
license = "GPL-3.0"
readme = "README.md"

[dependencies]
thiserror = { workspace = true }
bitflags  = { workspace = true }
smallvec  = { workspace = true }
rustc-hash = { workspace = true }
sha1      = { workspace = true }
adler     = { workspace = true }
memmap2   = { workspace = true }
tempfile  = { workspace = true }
rayon     = { workspace = true }
serde     = { workspace = true }
tracing   = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
criterion         = { workspace = true }
zip               = { version = "2", default-features = false, features = ["deflate"] }
smallvec          = { workspace = true }

[[bench]]
name = "dex_bench"
harness = false
