[package]
name = "reseam-dex"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "A high-performance DEX file parser, writer, and mutator"
license = "AGPL-3.0-or-later"
readme = "README.md"

[dependencies]
reseam-storage = { workspace = true }
thiserror = { workspace = true }
bitflags  = { workspace = true }
smallvec  = { workspace = true, features = ["union"] }
rustc-hash = { workspace = true }
ring      = { workspace = true }
zlib-rs   = { workspace = true }
tempfile  = { workspace = true }
rayon     = { workspace = true }
tracing   = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }

[lints]
workspace = true
