[package]
name = "reseam-apk"
version.workspace = true
edition = "2021"
description = "APK container support for Reseam: ZIP, AXML, resources, and DEX extraction"
readme = "README.md"

[dependencies]
reseam-dex = { workspace = true }
rustc-hash = { workspace = true }
serde      = { workspace = true }
serde_json = { workspace = true }
smallvec   = { workspace = true }
thiserror  = { workspace = true }
zip        = { workspace = true }
quick-xml  = { workspace = true }
rayon      = { workspace = true }
tracing    = { workspace = true }
memmap2    = { workspace = true }
tempfile   = { workspace = true }
flate2     = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true }

[dev-dependencies]
reseam-sign = { workspace = true }
