[package]
name = "reseam-sdk"
version.workspace = true
edition = "2021"
description = "Application integration SDK for Reseam clients"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
boltffi        = { workspace = true }
reseam-apk     = { workspace = true }
reseam-sign    = { workspace = true }
reseam-patcher = { workspace = true }
anyhow         = { workspace = true }
serde          = { workspace = true }
serde_json     = { workspace = true }
hex            = { workspace = true }
jni            = { workspace = true }
tracing        = { workspace = true }
libc           = { workspace = true }
