[package]
name = "reseam_patcher"

[targets.apple]
enabled = false

[targets.wasm]
enabled = false

[targets.android]
enabled = true

[targets.android.kotlin]
package = "app.reseam.patch"
output = "../../patch-api/generated"
module_name = "ReseamPatcher"
library_name = "reseam_patcher"
