[package]
name = "stitch-patcher"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
stitch-apk          = { workspace = true }
stitch-patcher-macros = { workspace = true }
thiserror   = { workspace = true }
serde       = { workspace = true }
toml        = { workspace = true }
smallvec    = { workspace = true }
boltffi     = { workspace = true, optional = true }
jni         = { workspace = true, optional = true }
zip         = { workspace = true }
anyhow      = { workspace = true }


[dev-dependencies]
tempfile = { workspace = true }

[features]
default = ["kotlin"]
kotlin = ["dep:boltffi", "dep:jni"]

[build-dependencies]
cc = "1"
